<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subscriber Agreement - Theta Data</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/header.css">
</head>
<body>

<?php require_once('../partials/header.php'); ?>

<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <h1 class="display-4 mb-4">Theta Data Subscriber Agreement</h1>
            <p class="lead">This Data License Agreement (this "Agreement"), effective as of (the "Effective Date"), is by and between AxiomX, a New York limited liability company with offices located at 74 Carpenter Avenue, Sea Cliff, New York ("Licensor") and you ("Licensee"). Licensor and Licensee may be referred to herein collectively as the "Parties" or individually as a "Party."</p>
            
            <h2 class="mt-5">WHEREAS</h2>
            <p>Licensor has compiled data into the proprietary data compilation described in Exhibit A, and such proprietary data compilation is referred to in this Agreement as (the "Data"); and</p>
            <p>Licensor desires to license the Data to Licensee, and Licensee desires to license the Data from Licensor, subject to the terms and conditions of this Agreement.</p>
            
            <h2 class="mt-5">NOW, THEREFORE</h2>
            <p>In consideration of the mutual covenants, terms, and conditions set forth herein, and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the Parties agree as follows:</p>

            <h3 class="mt-4">1. License</h3>
            <p><strong>(a) License Grant.</strong> Subject to and conditioned on Licensee's payment of Fees and compliance with all other terms and conditions of this Agreement, Licensor hereby grants Licensee a non-exclusive, non-sublicensable, and non-transferable (except in compliance with Section 9(g)) license during the Term to use the Data solely for Licensee's internal personal use purposes/the permitted use set forth in Exhibit A (the "Permitted Use"). The total number of users/amounts of usage by the Licensee will not exceed the limits set forth in Exhibit A, except as expressly agreed to in writing by the Parties and subject to any appropriate adjustment of the fees payable hereunder.</p>
            <p><strong>(b) Use Restrictions.</strong> Licensee shall only use the Data for the Permitted Use and shall not disclose, release, distribute, or deliver the Data, or any portion thereof, to any third party without Licensor's prior written consent. Any purpose or use not specifically authorized herein is prohibited unless otherwise agreed to in writing by Licensor. Without limiting the foregoing and except as otherwise expressly set forth in this Agreement, Licensee shall not at any time, directly or indirectly: (i) copy, modify, or create derivative works of the Data, in whole or in part; (ii) rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Data; (iii) reverse engineer, disassemble, decompile, decode, adapt, or otherwise attempt to derive or gain access to the source of the Data or methods used to compile the Data, in whole or in part; (iv) remove any proprietary notices included within the Data; (v) publish, enhance, or display any compilation or directory based upon information derived from the Data; or (vi) use the Data in any manner or for any purpose that infringes, misappropriates, or otherwise violates any intellectual property right or other right of any person, or that violates any applicable law.</p>
            <p><strong>(c) Reservation of Rights.</strong> Licensor reserves all rights not expressly granted to Licensee in this Agreement. Except for the limited rights and licenses expressly granted under this Agreement, nothing in this Agreement grants, by implication, waiver, estoppel, or otherwise, to Licensee or any third party any intellectual property rights or other right, title, or interest in or to the Data.</p>
            <p><strong>(d) Delivery.</strong> Licensor shall deliver the Data electronically, on tangible media, or by other means, in Licensor's sole discretion, on an intra-day basis to Licensee. Risk of loss of any tangible media on which the Data is delivered will pass to Licensee on delivery to carrier.</p>

            <h3 class="mt-4">2. Fees and Payment</h3>
            <p><strong>(a) Fees.</strong> Licensee shall pay Licensor the fees ("Fees") set forth in Exhibit A without offset or deduction. Licensee shall make all payments hereunder in US dollars on or before the due date set forth in Exhibit A. If Licensee fails to make any payment when due, in addition to all other remedies that may be available: (i) Licensor may charge interest on the past due amount at the rate of 1% per day calculated daily and compounded daily or, if lower, the highest rate permitted under applicable law; and (ii) Licensee shall reimburse Licensor for all reasonable costs incurred by Licensor in collecting any late payments or interest, including attorneys' fees, court costs, and collection agency fees; and (iii) if such failure continues for 30 days following written notice thereof, Licensor may prohibit access to the Data until all past due amounts and interest thereon have been paid, without incurring any obligation or liability to Licensee or any other person by reason of such prohibition of access to the Data; and (iv) At Licensor’s discretion, Licensor has the unilateral right to terminate service/prohibit access to the Data immediately after a payment is overdue, superseding the aforementioned items.</p>
            <p><strong>(b) Taxes.</strong> All Fees and other amounts payable by Licensee under this Agreement are exclusive of taxes and similar assessments. Licensee is responsible for all sales, use and excise taxes, and any other similar taxes, duties and charges of any kind imposed by any federal, state, or local governmental or regulatory authority on any amounts payable by Licensee hereunder, other than any taxes imposed on Licensor's income.</p>
            <p><strong>(c) Auditing Rights and Required Records.</strong> Licensee agrees to maintain complete and accurate records in accordance with generally accepted accounting principles during the Term and for a period of two years after the termination or expiration of this Agreement with respect to matters necessary for accurately determining amounts due hereunder. Licensor may, at its own expense, on reasonable prior notice, periodically inspect and audit Licensee's records with respect to matters covered by this Agreement, provided that if such inspection and audit reveals that Licensee has underpaid Licensor with respect to any amounts due and payable during the Term, Licensee shall promptly pay the amounts necessary to rectify such underpayment, together with interest in accordance with Section 2(a). Licensee shall pay for the costs of the audit if the audit determines that Licensee's underpayment equals or exceeds 5% for any quarter. Such inspection and auditing rights will extend throughout the Term of this Agreement and continue for a period of two years after the termination or expiration of this Agreement.</p>

            <h3 class="mt-4">3. Confidential Information and Data Security</h3>
            <p><strong>(a) Confidential Information.</strong> From time to time during the Term, either Party may disclose or make available to the other Party information about its affairs, products, confidential intellectual property, trade secrets, third-party confidential information, and other sensitive or proprietary information, whether orally or in written, electronic, or other form or media/in written or electronic form or media, that is/and whether or not marked, designated, or otherwise identified as "confidential" (collectively, "Confidential Information"). Without limiting the foregoing, for purposes of this Agreement, the Data will be deemed Confidential Information of Licensor. Confidential Information does not include information that, at the time of disclosure is: (i) in the public domain; (ii) known to the receiving Party at the time of disclosure; (iii) rightfully obtained by the receiving Party on a non-confidential basis from a third party; or (iv) independently developed by the receiving Party. The receiving Party shall not disclose the disclosing Party's Confidential Information to any person or entity, except to the receiving Party's employees who have a need to know the Confidential Information for the receiving Party to exercise its rights or perform its obligations hereunder. Notwithstanding the foregoing, each Party may disclose Confidential Information to the limited extent required (x) in order to comply with the order of a court or other governmental body, or as otherwise necessary to comply with applicable law, provided that the Party making the disclosure pursuant to the order shall first have given written notice to the other Party and made a reasonable effort to obtain a protective order; or (y) to establish a Party's rights under this Agreement, including to make required court filings. On the expiration or termination of this Agreement, the receiving Party shall promptly return to the disclosing Party all copies, whether in written, electronic, or other form or media, containing the disclosing Party's Confidential Information and, on request, certify in writing to the disclosing Party that such Confidential Information has been returned or destroyed.</p>
            <p><strong>(b) Data Security.</strong> Licensee shall use all reasonable legal, organizational, physical, administrative, and technical measures, and security procedures to safeguard and ensure the security of the Data and to protect the Data from unauthorized access, disclosure, duplication, use, modification, or loss.</p>

            <h3 class="mt-4">4. Intellectual Property Ownership</h3>
            <p>Licensee acknowledges that, as between Licensee and Licensor, Licensor and/or Licensor’s affiliates owns all right, title, and interest, including all intellectual property rights, in and to the Data. Licensee further acknowledges that: (a) the Data is an original compilation protected by United States copyright laws; (b) Licensor has dedicated substantial resources to collect, manage, and compile the Data; and (c) the Data constitutes trade secrets of Licensor and/or Licensor’s affiliates. Licensor may terminate this Agreement without advance notice to Licensee or an opportunity for Licensee to cure and without further obligation or liability if Licensee contests any of Licensor's right, title, or interest in or to the Data, including without limitation, in a judicial proceeding anywhere throughout the world.</p>

            <h3 class="mt-4">5. Disclaimer of Warranties</h3>
            <p class="text-uppercase">The data is provided "as is" and licensor hereby disclaims all warranties, whether express, implied, statutory, or otherwise. Licensor specifically disclaims all implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement, and all warranties arising from course of dealing, usage, or trade practice. Licensor makes no warranty of any kind that the data, or any products or results of its use, will meet licensee's or any other person's requirements, operate without interruption, achieve any intended result, be compatible or work with any software, system, or other services, or be secure, accurate, complete, free of harmful code, or error free.</p>

            <h3 class="mt-4">6. Indemnification</h3>
            <p><strong>(a) Licensee Indemnification.</strong> Licensee shall indemnify, hold harmless, and, at Licensor's option, defend Licensor from and against any Losses resulting from any Third-Party Claim based on Licensee's: (i) negligence or willful misconduct; or (ii) use of the Data in a manner not authorized by this Agreement, provided that Licensee may not settle any Third-Party Claim against Licensor unless such settlement completely and forever releases Licensor from all liability with respect to such Third-Party Claim or unless Licensor consents to such settlement, and further provided that Licensor shall have the right, at its option, to defend itself against any such Third-Party Claim or to participate in the defense thereof by counsel of its own choice.</p>
            <p><strong>(b) Sole Remedy.</strong> THIS SECTION 6 SETS FORTH LICENSEE'S SOLE REMEDIES AND LICENSOR'S SOLE LIABILITY AND OBLIGATION FOR ANY ACTUAL, THREATENED, OR ALLEGED CLAIMS THAT THE DATA INFRINGES, MISAPPROPRIATES, OR OTHERWISE VIOLATES ANY INTELLECTUAL PROPERTY RIGHTS OF ANY THIRD PARTY.</p>

            <h3 class="mt-4">7. Limitations of Liability</h3>
            <p class="text-uppercase">In no event will licensor be liable under or in connection with this agreement under any legal or equitable theory, including breach of contract, tort (including negligence), strict liability, and otherwise, for any (a) consequential, incidental, indirect, exemplary, special, enhanced, or punitive damages, (b) increased costs, diminution in value, or lost business, production, revenues, trading loss, or profits, (c) loss of goodwill or reputation, (d) use, inability to use, loss, interruption, delay, or recovery of any data or breach of data or system security, or (e) cost of replacement goods or services, in each case regardless of whether licensor was advised of the possibility of such losses or damages or such losses or damages were otherwise foreseeable. In no event will licensor's aggregate liability arising out of or related to this agreement, under any legal or equitable theory, including breach of contract, tort (including negligence), strict liability, and otherwise, exceed the total amounts paid and amounts accrued but not yet paid to licensor under this agreement in the one month period preceding the event giving rise to the claim or $20, whichever is less.</p>

            <h3 class="mt-4">8. Term and Termination</h3>
            <p><strong>(a) Term.</strong> The initial term of this Agreement begins on the Effective Date and, unless terminated earlier pursuant to any of this Agreement's express provisions, will continue in effect indefinitely.</p>
            <p><strong>(b) Termination.</strong> In addition to any other express termination right set forth elsewhere in this Agreement:</p>
            <ul>
                <li>Licensor may terminate this Agreement, effective when their data access is terminated, if Licensee: (A) fails to pay any amount when due hereunder; or (B) breaches any of its obligations under Section 1(b) or Section 3; or</li>
                <li>either Party may terminate this Agreement, effective on written notice to the other Party, if the other Party materially breaches this Agreement, and such breach: (A) is incapable of cure; or (B) being capable of cure, remains uncured 30 days after the non-breaching Party provides the breaching Party with written notice of such breach; or</li>
                <li>either Party may terminate this Agreement, effective immediately upon written notice to the other Party, if the other Party: (A) becomes insolvent or is generally unable to pay, or fails to pay, its debts as they become due; (B) files, or has filed against it, a petition for voluntary or involuntary bankruptcy or otherwise becomes subject, voluntarily or involuntarily, to any proceeding under any domestic or foreign bankruptcy or insolvency law; (C) makes or seeks to make a general assignment for the benefit of its creditors; or (D) applies for or has appointed a receiver, trustee, custodian, or similar agent appointed by order of any court of competent jurisdiction to take charge of or sell any material portion of its property or business.</li>
            </ul>
            <p><strong>(c) Effect of Expiration or Termination.</strong> Upon expiration or earlier termination of this Agreement, the license granted hereunder will also terminate, and, without limiting Licensee's obligations under Section 3, Licensee shall cease using and delete, destroy, or return all copies of the Data and certify in writing to the Licensor that the Data has been deleted or destroyed. No expiration or termination will affect Licensee's obligation to pay all Fees that may have become due before such expiration or termination, or entitle Licensee to any refund.</p>
            <p><strong>(d) Survival.</strong> Any rights, obligations, or required performance of the parties in this Agreement which, by their express terms or nature and context are intended to survive termination or expiration of this Agreement, will survive any such termination or expiration, including the rights and obligations set forth in this Section 8(d) and Section 2, Section 3, Section 4, Section 6, Section 7, and Section 9.</p>
            <p><strong>(e) Data Expungement.</strong> All data obtained indirectly or directly from Theta Data must be expunged within 30 days of termination of this Agreement. Data obtained indirectly or directly from Theta Data cannot be redistributed before or after the time of termination. Derived works generated from Theta Data cannot be redistributed before or after the time of termination, and must be expunged within 30 days after termination of this Agreement.</p>

            <h3 class="mt-4">9. Miscellaneous</h3>
            <p><strong>(a) Entire Agreement.</strong> This Agreement, together with any other documents incorporated herein by reference and all related Exhibits, constitutes the sole and entire agreement of the Parties with respect to the subject matter of this Agreement and supersedes all prior and contemporaneous understandings, agreements, and representations and warranties, both written and oral, with respect to such subject matter. In the event of any inconsistency between the statements made in the body of this Agreement, the related Exhibits, and any other documents incorporated herein by reference, the following order of precedence governs: (i) first, this Agreement, excluding its Exhibits; (ii) second, the Exhibits to this Agreement as of the Effective Date; and (iii) third, any other documents incorporated herein by reference.</p>
            <p><strong>(b) Notices.</strong> All notices, requests, consents, claims, demands, waivers, and other communications hereunder (each, a "Notice") must be in writing and addressed to the Parties at the addresses set forth on the first page of this Agreement (or to such other address that may be designated by each Party from time to time in accordance with this Section). The Parties shall deliver Notices by personal delivery, nationally recognized overnight courier (with all fees pre-paid), facsimile, or email (with confirmation of transmission) or certified or registered mail (in each case, return receipt requested, postage pre-paid). Except as otherwise provided in this Agreement, a Notice is effective only: (i) upon receipt by the receiving Party, and (ii) if the Party giving the Notice has complied with the requirements of this Section.</p>
            <p><strong>(c) Force Majeure.</strong> In no event shall Licensor be liable to Licensee, or be deemed to have breached this Agreement, for any failure or delay in performing its obligations under this Agreement, if and to the extent such failure or delay is caused by any circumstances beyond Licensor's control, including, without limitation, the following force majeure events: (i) acts of God; (ii) flood, fire, earthquake, or explosion; (iii) war, invasion, hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest; (iv) government order, law, or actions; (v) embargoes or blockades in effect on or after the date of this Agreement; (vi) national or regional emergency; (vii) strikes, labor stoppages or slowdowns, or other industrial disturbances; (viii) shortage of adequate power or transportation facilities; ix other similar events beyond the control of the Party.</p>
            <p><strong>(d) Amendment and Modification; Waiver.</strong> No amendment to or modification of this Agreement is effective unless it is in writing and signed by an authorized representative of each Party. No waiver by any Party of any of the provisions hereof will be effective unless explicitly set forth in writing and signed by the Party so waiving. Except as otherwise set forth in this Agreement, (i) no failure to exercise, or delay in exercising, any rights, remedy, power, or privilege arising from this Agreement will operate or be construed as a waiver thereof and (ii) no single or partial exercise of any right, remedy, power, or privilege hereunder will preclude any other or further exercise thereof or the exercise of any other right, remedy, power, or privilege.</p>
            <p><strong>(e) Severability.</strong> If any provision of this Agreement is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability will not affect any other term or provision of this Agreement or invalidate or render unenforceable such term or provision in any other jurisdiction. Upon such determination that any term or other provision is invalid, illegal, or unenforceable, the Parties shall negotiate in good faith to modify this Agreement so as to affect the original intent of the Parties as closely as possible in a mutually acceptable manner in order that the transactions contemplated hereby be consummated as originally contemplated to the greatest extent possible.</p>
            <p><strong>(f) Governing Law; Submission to Jurisdiction.</strong> This Agreement is governed by and construed in accordance with the internal laws of the State of New York without giving effect to any choice or conflict of law provision or rule that would require or permit the application of the laws of any jurisdiction other than those of the State of New York. Any legal suit, action, or proceeding arising out of or related to this Agreement or the licenses granted hereunder may be instituted exclusively in the federal courts of the United States or the courts of the State of New York in each case located in the city of Sea Cliff and County of Nassau, and each Party irrevocably submits to the jurisdiction of such courts in any such suit, action, or proceeding.</p>
            <p><strong>(g) Assignment.</strong> Licensee may not assign or transfer any of its rights or delegate any of its obligations hereunder, in each case whether voluntarily, involuntarily, by operation of law, or otherwise, without the prior written consent of Licensor, which consent shall not be unreasonably withheld, conditioned, or delayed. Any purported assignment, transfer, or delegation in violation of this Section is null and void. No assignment, transfer, or delegation will relieve the assigning or delegating Party of any of its obligations hereunder. This Agreement is binding upon and inures to the benefit of the Parties and their respective permitted successors and assigns.</p>
            <p><strong>(h) Export Regulation.</strong> The Data may be subject to US export control laws, including the Export Control Reform Act and its associated regulations. Licensee shall not, directly, or indirectly, export, re-export, or release the Data to, or make the Data accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, rule, or regulation. Licensee shall comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Data available outside the US.</p>
            <p><strong>(i) Equitable Relief.</strong> Each Party acknowledges and agrees that a breach or threatened breach by such Party of any of its obligations under Section 3 or, in the case of Licensee, Section 1(b) would cause the other Party irreparable harm for which monetary damages would not be an adequate remedy and agrees that, in the event of such breach or threatened breach, the other Party will be entitled to equitable relief, including a restraining order, an injunction, specific performance, and any other relief that may be available from any court, without any requirement to post a bond or other security, or to prove actual damages or that monetary damages are not an adequate remedy. Such remedies are not exclusive and are in addition to all other remedies that may be available at law, in equity, or otherwise.</p>
            <p><strong>(j) Counterparts.</strong> This Agreement may be executed in counterparts, each of which is deemed an original, but all of which together are deemed to be one and the same agreement.</p>

            <hr class="my-5">

            <h2 class="text-center mb-4">EXHIBIT A</h2>
            <p>Capitalized terms used but not defined in this Exhibit A have the meaning given to those terms in the Agreement.</p>
            <p><strong>A. DESCRIPTION OF DATA:</strong> Historical & intraday equities, equity options, and equity options analytics.</p>
            <p><strong>B. NUMBER OF USERS/AMOUNT OF USAGE:</strong> Licensee is permitted one individual to access the Data for the duration of their Term. A Licensee cannot accumulate multiple accounts and access the Data simultaneously.</p>
            <p><strong>C. PERMITTED USE(S):</strong> Use of the Data for the benefit of Licensee in the ordinary course of its internal personal use/the purpose of trading on Licensee’s behalf, analysis, and/or research. And follow the below terms set forth by OPRA (Options Price Reporting Authority). You, the subscriber…</p>
            <ol type="i">
                <li>shall receive OPRA Data solely for such person’s own use (including, in the case of a Professional Subscriber, the use of such person’s employees on behalf of such person),</li>
                <li>shall not retransmit or otherwise furnish OPRA Data to any other person (other than, in the case of a Professional Subscriber, such Professional Subscriber’s employees),</li>
                <li>acknowledges that OPRA Data is and shall remain the property of the respective exchange or other market on which a reported transaction took place or a reported quotation was entered,</li>
                <li>acknowledges the absence of any guarantee and the disclaimer of liability on the part of OPRA, the Processor and each Participant as stated in Section 12 of this Agreement,</li>
                <li>acknowledges that the terms and conditions of the Subscriber Agreement may be modified by OPRA at any time upon notice to the Subscriber, and</li>
                <li>acknowledges that the Subscriber Agreement may be terminated by the Subscriber or Vendor upon 30 days notice from the terminating party to the other -10- party, and may be terminated immediately by Vendor upon a determination by Vendor or OPRA that the Subscriber is not in compliance with the Subscriber Agreement.</li>
            </ol>
            <p><strong>D. FEES:</strong> A monthly fee is applied depending on your subscription tier. These fees are variable and by no means will remain the same in the future. For our fee schedule please visit <a href="https://thetadata.net/subscribe">https://thetadata.net/subscribe</a>.</p>
            <p><strong>E. SECURITY REQUIREMENTS:</strong> Licensee is not permitted to share their login credentials with ANYONE including but not limited to: relatives, friends, and colleagues</p>
        </div>
    </div>
</div>

<?php require_once('../partials/footer.php'); ?>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
