<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms & Conditions | Theta Data</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/custom-bootstrap.css">
</head>
<body>

    <?php include('../partials/header.php'); ?>

    <div class="container">
        <div class="policy-container">
            <h1>Terms & Conditions</h1>
            <hr>

            <p><strong>AxiomX LLC (“Licensor”)</strong> (together with our affiliates, “Theta Data”) provides a platform for accessing market data, analytics, pricing, and features. Entitlements to these services can be managed on the Theta Data websites, including <a href="https://www.thetadata.net/">https://www.thetadata.net/</a> (the “Site”), Theta Terminal, a desktop application, and the Theta Data API, an application programming interface (collectively, the “Services”). These Terms and Conditions (these “Terms”) constitute a legally binding agreement between the entity or organization that is subscribing to the Services (“Subscriber”) and Licensor. Licensor and Subscriber are sometimes referred to herein individually as a “Party” and together as the “Parties.”</p>

            <p>BY ACCESSING OR USING THE SERVICES, SUBSCRIBER REPRESENTS AND WARRANTS THAT SUBSCRIBER HAS READ AND UNDERSTOOD AND AGREES TO BE BOUND BY THESE TERMS, INCLUDING THEIR DISCLAIMERS AND LIMITATIONS OF LIABILITY, AND THAT SUBSCRIBER HAS THE LEGAL CAPACITY TO ENTER INTO A BINDING AGREEMENT. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS, DO NOT ACCESS OR USE THE SERVICES. These Terms do not purport to supersede any other legally binding agreements between Subscriber and Theta Data.</p>

            <h4>1. Scope of License.</h4>
            <p><strong>1.1 License Grant.</strong> Subject to Subscriber’s ongoing compliance with these Terms, Licensor hereby grants Subscriber a limited, revocable, non-exclusive, non-transferable right and license to access and use the Services solely for the personal, non-commercial use of Subscriber’s Authorized Users (as defined below). Licensor and its licensors reserve all rights not expressly granted in these Terms, including, without limitation, rights of title, ownership, intellectual property and all other rights and interests in the Services, the Content, and all related items.</p>

            <p><strong>1.2 Authorized Users.</strong> The license rights granted by Licensor to Subscriber under this Section 1 shall extend to Subscriber’s employees authorized by Subscriber (“Authorized Users”) solely for each Authorized User’s personal, non-commercial use, provided that as a condition of Subscriber’s right to authorize its employees to use the Services, Subscriber shall require, and Subscriber agrees to require, each Authorized User to agree in writing to, and shall comply with and be bound by, the terms and conditions of these Terms, including, without limitation, the provisions of Sections 7-10 of these Terms, the binding arbitration and class action waiver provisions set forth at Section 11, and any applicable terms of use or similar documents made available on Licensor’s Site, as may be updated at any time in Licensor’s sole discretion (collectively, “Authorized User Agreements”). Subscriber shall ensure that the Authorized User Agreements are enforceable against the Authorized User in accordance with applicable law, and Theta Data shall be the intended and express third-party beneficiary of all Authorized User Agreements. Each Authorized User must be at least eighteen (18) years old or the age of legal majority in his or her jurisdiction of residence to access and use the Service. Subscriber acknowledges and agrees that in using or authorizing the use by Authorized Users of the Services, Subscriber acts solely at its own risk and as between the Parties, Subscriber shall have sole liability and responsibility under and in connection with the Authorized User Agreements and any authorizations, sublicenses or other agreements entered into by it, including, without limitation, in respect of any warranties given or indemnification obligations undertaken in or pursuant to such authorization, sublicense or agreement, and shall indemnify, defend and hold harmless Theta Data from and against any and all claims asserted against Theta Data by Subscriber’s Authorized Users or other third parties arising out of or in connection with such agreements or authorizations.</p>

            <h4>2. Restrictions on Use.</h4>
            <p><strong>2.1 Restrictions.</strong> Subscriber’s and each Authorized User’s use of the Services, including all features and functionalities associated therein, shall be in accordance with all applicable laws, rules, and regulations, or other restrictions on use of the Services or its Content. Subscriber and each Authorized User shall comply with these Terms and shall not: (i) archive, download, reproduce, distribute, modify, display, perform, publish, license, create derivative works of, or offer for sale the Services or any Content or information contained in or obtained from or through the Services; (ii) delete the copyright or other proprietary rights notices from the Services or any Content; (iii) circumvent, remove, alter, deactivate, degrade or thwart any of the content or other protections enabled on the Services, including, but not limited to, any territorial restrictions such as IP address-based restrictions; (iv) use any robot, spider, scraper or other automated means to access the Services; (v) decompile, reverse engineer or disassemble any software or other products or processes accessible through the Services; (vi) insert any code or product or manipulate the Services in any way; (vii) use any data mining, data gathering or extraction method; (viii) upload, post, e-mail or otherwise send or transmit any material designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment associated with the Services, including any software viruses or any other computer code, files or programs; (ix) remove, modify, disable, block, impair, or obscure any advertising in connection with the Services; (x) use or encourage the use of the Services or its Content for any illegal purpose, or in violation of any local, state, national, or international law, including, without limitation, laws governing intellectual property and other proprietary rights, data protection and privacy; (xi) use any of Theta Data’s marks or any third-party marks, or any marks that are confusingly similar to such marks, in any way that suggests that Theta Data or any third party endorses or is affiliated with Subscriber or any third party, or in any way that is likely to cause confusion, mistake or deception; or (xii) use the Services or its Content for any commercial purpose not expressly approved by Licensor in writing.</p>

            <h4>3. Privacy; Data.</h4>
            <p><strong>3.1 Privacy Policy.</strong> The Theta Data Privacy Policy, which is available on the Site, governs any information submitted via the Services and is incorporated by reference into these Terms. All other policies posted on the Site by Licensor are also incorporated into these Terms by reference. Each reference to these Terms herein includes reference to the Privacy Policy and all other policies posted on the Site. Subscriber shall comply with these policies when accessing or using the Services.</p>

            <p><strong>3.2 Aggregated Data.</strong> The Parties acknowledge and agree that Company shall have the right to collect, extract, compile, analyze, use and commercialize: (i) in an aggregated, de-identified, anonymized format, any and all data used by Licensor in connection with the Services or submitted by Subscriber or any Authorized User, including, but not limited to, demographics, wellness objectives and other identifying information; and (ii) any non-personally identifiable information or data resulting from Subscriber’s or its Authorized Users’ use of the Services (collectively, “Aggregated Data”). Subscriber hereby grants to Licensor the worldwide, non-exclusive, freely transferable, royalty-free, perpetual, irrevocable right and license (with right to sublicense) to use, reproduce, electronically distribute, store, process, and display the Aggregated Data for any purpose.</p>

            <h4>4. Account Registration; Security.</h4>
            <p><strong>4.1 Registration.</strong> Licensor may make available certain Services that enable or require Subscriber or its Authorized Users to register an account with Licensor (an “Account”). Registering an Account requires Subscriber or its Authorized User to provide Licensor with certain true, accurate, and complete information. The Account holder shall be responsible for updating and maintaining the accuracy of the information provided to us relating to the Account. By registering for an Account, each Authorized User confirms that he or she is at least eighteen (18) years old or the age of legal majority in his or her jurisdiction of residence.</p>

            <p><strong>4.2 Security.</strong> Persons who have access to password-protected Services are responsible for maintaining the confidentiality of any Account information, user names, and security questions and answers that they may use to access any page or feature of the password-protected area, and for logging off any protected areas of the Services. Accordingly, each Account holder shall take steps to protect the confidentiality of any passwords and shall notify Licensor immediately if such Account holder becomes aware of any disclosure, loss, theft or unauthorized use of a password. Theta Data makes no warranty, express or implied, regarding the security of the Services, including with respect to the ability of unauthorized persons to intercept or access information transmitted by or to any Account holder through the Services.</p>

            <h4>5. Intellectual Property.</h4>
            <p><strong>5.1 Licensor Rights in Content.</strong> Except as expressly set forth herein, all intellectual property rights in and to all text, graphics, images, video, audio, software, interfaces, photographs, works of authorship of any kind, Feedback (as defined below), and information or other materials that are posted, generated, provided or otherwise made available through the Services, and the selection and arrangement thereof, any enhancements to or derivative works thereto, and the features and functionality of the Services (collectively, “Content”) are the exclusive property of Licensor or its licensors and are protected by U.S. and international laws. Nothing in these Terms grants to Subscriber any ownership or use rights with respect to Content except for the license expressly granted in these Terms. Subscriber shall not take any actions to claim or assert ownership of any Content or seek to register intellectual property rights in or to any Content. All rights not expressly granted are hereby reserved. To the maximum extent permitted by law, Licensor makes no representations or warranties with respect to any Content made available through the Services.</p>

            <p><strong>5.2 Feedback.</strong> For purposes of these Terms, “Feedback” means any content, comments or suggestions about improving or adding new features or functionalities to the Services, and any feedback, reviews or testimonials regarding the Services, made or provided by Subscriber or its Authorized Users. Any Feedback, whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such Feedback. Subscriber represents that all Feedback submitted by or on behalf of Subscriber or its Authorized Users is accurate, complete, up-to-date, and in compliance with these Terms and with all applicable laws, rules and regulations. As between Subscriber and Licensor, Subscriber represents and warrants that Subscriber owns or has all rights necessary to grant Licensor the rights below to all Feedback that Subscriber or its Authorized Users submit to or through the Services. Subscriber hereby grants Licensor a worldwide, perpetual, irrevocable, non-exclusive, sublicensable (through multiple tiers), transferable royalty-free license and right to use, copy, transmit, distribute, publicly perform and display (through all media now known or later created), edit, modify, exploit, and make derivative works from Feedback for any purpose whatsoever, commercial or otherwise, without compensation. Theta Data is not responsible or liable for the removal or deletion of or the failure to remove or delete any Feedback.</p>

            <p><strong>5.3 Theta Data Trademarks.</strong> THETADATA™ is a proprietary service mark of AxiomX, and other marks displayed in the Content or through the Services may be owned by third parties. Licensor’s use of third-party marks is not intended and should not be deemed to constitute an endorsement or recommendation of any third-party product or service.</p>

            <h4>6. Third-Party Materials and Applications.</h4>
            <p><strong>6.1 Use of Third-Party Content and Applications.</strong> Theta Data may provide through the Services links to other websites on the Internet or materials or information that is owned and operated by third parties. In addition, certain third-party applications, including, without limitation, websites, widgets, software or software utilities, may interact with the Services. Subscriber acknowledges and agrees that Theta Data is not responsible for the availability of, or the materials or information located on or through, any third-party website or application. The selection or omission of links is not intended to endorse any particular companies, products or services. Any use of or access to any third-party websites or applications linked to or made available through the Services is at the sole risk of Subscriber. Subscriber acknowledges and agrees that Subscriber should contact the website administrator or webmaster for any such third-party websites or applications if Subscriber has any concerns regarding such links or the materials or information located on such websites or within such application. Any use of third-party websites and applications may be subject to third-party terms of use, privacy policies and license terms, which Subscriber is encouraged to review.</p>

            <h4>7. Disclaimer of Warranties.</h4>
            <p><strong>7.1 Disclaimer of Warranties.</strong> THETA DATA MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO THE SERVICES OR ANY OTHER CONTENT, INFORMATION OR MATERIALS PROVIDED BY THETA DATA, ALL OF WHICH IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. To the fullest extent permitted by applicable law, Theta Data expressly disclaims all representations and warranties, express, implied, statutory or otherwise, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties arising out of usage of trade, course of dealing or course of performance. Specifically, but without limitation, Theta Data does not represent or warrant that: (i) the Services or any Content, information or results on or provided through the Services are correct, accurate, reliable, up-to-date or suitable for any wellness, healthcare, or medical purpose; (ii) access to and use of the Services shall be uninterrupted or error-free; (iii) the Services or the server that makes them available is free of viruses or other harmful components or defects or that defects shall be corrected; (iv) concerning any Content, including Feedback; or (v) the Services will meet Subscriber’s or any Authorized User’s personal or professional needs.</p>

            <h4>8. Limitation of Liability.</h4>
            <p><strong>8.1 Limitation of Liability.</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW: (I) IN NO EVENT SHALL THETA DATA OR ANY OF ITS PREDECESSORS, SUCCESSORS, PARENTS, SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, SHAREHOLDERS, INVESTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, ATTORNEYS AND THEIR RESPECTIVE HEIRS, SUCCESSORS AND ASSIGNS (THE “THETA DATA PARTIES”) BE LIABLE FOR ANY LOST PROFITS OR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR OTHER DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE ACCESS TO OR USE OF THE SERVICES, ANY DELAY IN OR INABILITY TO USE THE SERVICES, FOR ANY CONTENT, INFORMATION, SOFTWARE, PRODUCTS AND SERVICES ADVERTISED IN OR OBTAINED THROUGH THE SERVICES, OR OTHERWISE ARISING OUT OF THE USE OF THE SERVICES, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF THE THETA DATA PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES OR INJURY ARISING FROM ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, FILE CORRUPTION, COMMUNICATION-LINE FAILURE, NETWORK OR SYSTEM OUTAGE, OR THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF ANY RECORD; AND (II) IN NO EVENT SHALL THE AGGREGATE LIABILITY OF THE THETA DATA PARTIES EXCEED THE GREATER OF FIVE HUNDRED DOLLARS ($500) OR THE AMOUNT ACTUALLY PAID BY SUBSCRIBER TO LICENSOR OVER THE THREE (3) MONTH PERIOD PRECEDING THE DATE THAT SUCH CLAIMS AROSE. THE FOREGOING EXCLUSIONS AND LIMITATIONS ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN SUBSCRIBER AND LICENSOR.</p>

            <h4>9. Financial Advice.</h4>
            <p><strong>9.1 No Financial Advice.</strong> THE SERVICES ARE DESIGNED FOR EDUCATIONAL AND ENTERTAINMENT PURPOSES ONLY. THE USE OF INFORMATION PROVIDED THROUGH THE SERVICES IS SOLELY AT THE RISK OF SUBSCRIBER AND EACH AUTHORIZED USER. THETA DATA DOES NOT PROVIDE INVESTMENT ADVICE NOR ENDORSE ANY SECURITY OFFERING OR RECOMMENDATIONS. NOTHING PROVIDED BY THETA DATA OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICES IS INTENDED TO BE, AND SHALL NOT BE TAKEN TO BE, THE PRACTICE OF FINANCIAL ADVICE. AUTHORIZED USERS SHOULD CONSULT THEIR FINANCIAL ADVISORS BEFORE MAKING INVESTMENT DECISIONS USING THE SERVICES.</p>

            <h4>10. Indemnification; Insurance.</h4>
            <p><strong>10.1 Indemnification by Subscriber.</strong> Subscriber shall indemnify and hold harmless the Theta Data Parties from and against any and all claims, actions, suits, losses, liabilities, expenses, damages, and costs, including reasonable attorneys’ fees and costs, arising from or relating to: (i) access to or use of the Services, including, but not limited to, with respect to any bodily injury, physical harm, loss, illness, death or property damage; (ii) Subscriber’s actual or alleged breach of these Terms, including, without limitation, failure to comply with or satisfy Section 1.2; (iii) any Feedback submitted by or on behalf of Subscriber or any Authorized User; or (iv) infringement by Subscriber or any other user of the Services using Subscriber’s or any Authorized User’s computer or account of any intellectual property or any other right of any person or entity. Subscriber shall cooperate as fully as reasonably required in the defense of any such claim. Licensor reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by Subscriber. Each of the Theta Data Parties is an express third-party beneficiary of this indemnification provision, with full rights to enforce its terms.</p>

            <h4>11. Binding Arbitration; Class Action Waiver.</h4>
            <p><strong>11.1 Mandatory Arbitration.</strong> Any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Services (collectively, “Disputes”) shall be resolved through binding and final arbitration in accordance with the Commercial Arbitration Rules of the American Arbitration Association then in effect (the “Rules”); provided, however, that each Party shall retain the right to seek injunctive or other equitable relief from a court to prevent or enjoin the infringement or misappropriation of our respective intellectual property rights.</p>

            <p><strong>11.2 Informal Resolution.</strong> Subscriber agrees that before initiating any Dispute or arbitration proceeding, the Parties will attempt to negotiate an informal resolution of any Dispute. To begin this process, before initiating any arbitration proceeding, Subscriber must send a Notice of Dispute (“Notice”) by certified mail to the attention of “Theta Data Legal” at the Licensor address set out in Section 13.3 below. In the Notice, Subscriber must describe the nature and basis of the Dispute and the relief Subscriber is seeking. If the Parties are unable to resolve the Dispute within forty-five (45) days after Licensor’s receipt of the Notice, then Subscriber or Licensor may initiate arbitration proceedings as set out in this Section 11.</p>

            <p><strong>11.3 Terms of Arbitration.</strong> All statutes of limitation which otherwise would be applicable in a judicial action brought by a Party shall apply to any arbitration proceeding hereunder. The arbitration shall be decided by a panel of three (3) arbitrators selected under the Rules. Arbitration shall be initiated and conducted in the State of New York, and the arbitrators shall be bound to adjudicate all disputes in accordance with the laws of the State of New York. The award or decision rendered by the arbitrators shall be in writing with written findings of fact and shall be final and binding on the Parties. The arbitration agreement herein among the Parties shall be enforceable under applicable law in any court having jurisdiction thereof. Neither Party shall appeal such award nor seek review, modification, or vacation of such award in any court or regulatory agency. The prevailing Party shall be entitled to recover from the other Party its expenses for the arbitrators’ fees, attorneys’ fees and travel expenses, expert testimony and travel expenses of experts, and for all other expenses of presenting its case.</p>

            <p><strong>11.4 Class Action Waiver.</strong> SUBSCRIBER AND LICENSOR AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, if any Dispute is resolved through arbitration, the arbitrator shall not consolidate another person’s claims with Subscriber’s claims or otherwise preside over any form of a representative or class proceeding for any purpose. If this specific provision is found to be unenforceable, then the entirety of this Section 11 shall be null and void.</p>

            <h4>12. Cessation of Service; Termination.</h4>
            <p><strong>12.1 Termination.</strong> Licensor reserves the right to modify, terminate and suspend the operation of the Services, as well as the provision of any or all products, services or Content via the Services, without notice or liability, at any time and for any or no reason in its sole and absolute discretion. The rights granted to Subscriber herein shall, at Licensor’s option, terminate immediately upon any violation of law or these Terms, or upon expiration or termination of Subscriber’s subscription to access and use the Services, without prejudice to any other rights or remedies of Licensor. Licensor reserves the right to terminate Subscriber’s or any Authorized User’s access to and use of the Services at any time for any reason without notice or liability to Subscriber or any third party.</p>

            <p><strong>12.2 Effect of Termination.</strong> Upon termination of these Terms: (i) the license granted hereunder and all other provisions of these Terms shall terminate and Subscriber and its Authorized Users shall immediately cease using the Services; and (ii) Subscriber shall promptly remove any and all Services from its technical and/or cloud environment, destroy any and all hard copies thereof and, within thirty (30) days of the date of termination, certify to Licensor in writing such removal and destruction.</p>

            <h4>13. General Terms.</h4>
            <p><strong>13.1 Governing Law.</strong> These Terms shall be governed by and construed in accordance with the laws of the State of New York, without regard to principles of conflicts of law. The Uniform Commercial Code, the Uniform Computer Information Transaction Act, and the United Nations Convention of Controls for International Sale of Goods shall not apply.</p>

            <p><strong>13.2 Force Majeure.</strong> Licensor shall not be liable for any failure or delay in the performance of its obligations under these Terms if such failure or delay is on account of causes beyond its control, including, but not limited to, “acts of God,” labor disputes, civil commotion, war, fires, floods, inclement weather, governmental regulations or controls, pandemics, casualty, government authority, strikes, or computer attacks or malicious acts, such as attacks on or through the internet, any internet service provider, telecommunications or hosting facility in which event Licensor shall be excused from its obligations for the period of the delay and for a reasonable time thereafter.</p>

            <p><strong>13.3 Notice.</strong> Licensor may deliver notice to Subscriber under these Terms by means of e-mail, a general notice on its website, or by written communication delivered by first class postage prepaid international mail to Subscriber’s address or contact information on record in Licensor’s account information. Subscriber may give notice to Licensor at any time via e-mail to <a href="mailto:bailey@thetadata.net">bailey@thetadata.net</a> or by letter delivered by first class postage prepaid mail or overnight carrier to the following address: 74 Carpenter Avenue, Sea Cliff, New York 11579, USA</p>

            <p><strong>13.4 Entire Agreement.</strong> These Terms contain the entire agreement between the Parties with respect to the subject matter hereof, and supersede all prior and contemporaneous representations, promises, agreements and understandings, whether oral or written, between the Parties concerning the subject matter hereof. Subscriber may from time to time enter into binding legal agreements relating to certain products or services available from Theta Data, which may have terms that are different from those of these Terms. In the event of any inconsistency, the terms of such other agreement shall control with respect to such products or services.</p>

            <p><strong>13.5 Successors; Assignment; No Third-Party Beneficiaries.</strong> These Terms are binding upon and shall inure to the benefit of both Parties and their respective successors, heirs, executors, administrators, personal representatives, and permitted assigns. Subscriber shall not assign or transfer these Terms or any right or obligation hereunder, in whole or in part, by operation of law or otherwise, without Licensor’s prior written consent. Licensor may assign or transfer these Terms or its rights or obligations hereunder, in whole or in part, by operation of law or otherwise, at any time in its sole discretion without notice to Subscriber.</p>

            <p><strong>13.6 Waiver.</strong> Any waiver of any provision of these Terms shall be effective only if in writing and signed by Licensor. Any failure to enforce any provision of these Terms shall not constitute a waiver of a future breach of that or any other provision of these Terms.</p>

            <p><strong>13.7 Severability.</strong> Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, in certain jurisdictions, some of the above limitations of liability may not apply to Subscriber or to Authorized Users. In any such case, or if any terms or conditions of these Terms are held to be invalid or unenforceable, the remaining provisions of these Terms shall be valid and binding and of like effect as though such provision were not included. Furthermore, if any term or condition of this Agreement is found by an arbitral tribunal or a court to be invalid or unenforceable, the parties nevertheless agree and request that the arbitrator or court should modify such provision to the minimum extent necessary to render such provision valid and enforceable.</p>

            <p><strong>13.8 Amendment.</strong> Licensor may, in its sole discretion, revise these Terms at any time with or without additional notice to Subscriber. Such revised Terms shall be effective when posted on the Site. Subscriber should revisit these Terms on a regular basis, as revised versions will be binding upon Subscriber. Subscriber understands and agrees that Subscriber’s continued access to or use of the Services after the effective date of changes to these Terms indicates Subscriber’s acceptance of such revisions.</p>

            <h4>14. Refund and Cancellation Policy.</h4>
            <p><strong>14.1 Subscription Cancellations.</strong> Subscribers are responsible for managing their own subscriptions. To prevent automatic renewal, cancellations must be completed before the next billing cycle begins. Theta Data is not responsible for canceling subscriptions on behalf of users. Failure to cancel prior to renewal will result in charges for the next billing cycle, and no refunds will be issued.</p>

            <p><strong>14.2 Refund Policy.</strong> All payments for subscriptions are non-refundable. Refunds may be granted only in exceptional circumstances and solely at the discretion of Theta Data. If a refund is approved, it will be processed minus any applicable transaction fees, processing costs, or administrative fees.</p>

            <p><strong>14.3 No Partial or Pro-Rated Refunds.</strong> Theta Data does not offer partial or pro-rated refunds for any unused portion of a subscription period. If a subscriber cancels their membership, access to the service will continue until the end of the current billing cycle, but no refunds will be provided for unused time.</p>

            <p><strong>14.4 Chargebacks and Payment Disputes.</strong> Subscribers agree to contact Theta Data before initiating a chargeback or dispute with their payment provider. If a chargeback is initiated without prior communication, Theta Data reserves the right to suspend or permanently terminate the subscriber’s account.</p>

            <p>By subscribing to Theta Data, you acknowledge and agree to this Refund and Cancellation Policy. For any questions or assistance, please contact <a href="mailto:support@thetadata.net">support@thetadata.net</a>.</p>
        </div>
    </div>

    <?php include('../partials/footer.php'); ?>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
